# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\screens\changedate_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import os
import subprocess

base_dir = os.path.dirname(__file__)

class ChangeTime(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 206)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/clock.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 100, 431, 31))
        self.lineEdit.setStatusTip("")
        self.lineEdit.setWhatsThis("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 140, 431, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(self.ChangeTime)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def ChangeTime(self):
        time = self.lineEdit.text()
        os.system(f'C:/Glassy/platform_tools/adb.exe shell settings put global auto_time 0')
        os.system(f'C:/Glassy/platform_tools/adb.exe shell "toolbox date -s {time}"')
        os.system(f'C:/Glassy/platform_tools/adb.exe reboot')

        msg = QMessageBox()

        msg.setWindowTitle("Done")
        msg.setText("Done! Rebooting your Google Glass")

        msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Glassy"))
        self.label_2.setText(_translate("MainWindow", "Change date and time"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "YYYYMMDD.HHMMSS"))
        self.pushButton.setText(_translate("MainWindow", "Change"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ChangeTime()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
