# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\screens\uninstall_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtGui import QFontDatabase
import os
import shutil
import subprocess


base_dir = os.path.dirname(__file__)


class Remove(object):
    def setupUi(self, MainWindow):
        font_path = os.path.join(base_dir, "./fonts/Roboto_Condensed-Medium.ttf")
        font_id = QFontDatabase.addApplicationFont(font_path)
        font_families = QFontDatabase.applicationFontFamilies(font_id)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 521)
        MainWindow.setMinimumSize(QtCore.QSize(347, 521))
        MainWindow.setMaximumSize(QtCore.QSize(347, 521))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 411, 81))
        self.frame.setStyleSheet("background-color: rgb(79, 79, 79);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(25, 25, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 100, 321, 361))
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 470, 321, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        command = subprocess.run(
            ["C:/Glassy/platform_tools/adb.exe", "shell", "pm", "list", "packages"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )

        for line in command.stdout.splitlines():
            if line != "":
                self.listWidget.addItem(line)

        self.pushButton.clicked.connect(self.DeleteApp)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def DeleteApp(self):
        self.pushButton.setText("Uninstalling...")
        app_id = self.listWidget.currentItem().text()
        if "package:" in app_id:
            os.system(f"C:/Glassy/platform_tools/adb.exe uninstall {app_id.replace("package:", "")}")
            self.pushButton.setText("Uninstall")
            msg = QMessageBox()

            msg.setWindowTitle("Done")
            msg.setText(f"{app_id} was successfully uninstalled!")

            msg.exec_()
        else:
            os.system(f"C:/Glassy/platform_tools/adb.exe uninstall {app_id}")
            self.pushButton.setText("Uninstall")
            msg = QMessageBox()

            msg.setWindowTitle("Done")
            msg.setText(f"{app_id} was successfully uninstalled!")

            msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Glassy"))
        self.label_2.setText(_translate("MainWindow", "Uninstall app"))
        self.pushButton.setText(_translate("MainWindow", "Uninstall"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Remove()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
