# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\screens\firmwares.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from PyQt5.QtGui import QFontDatabase

import os
import shutil
import re

base_dir = os.path.dirname(__file__)


class Firmwares(object):
    def setupUi(self, MainWindow):
        font_path = os.path.join(base_dir, "./fonts/Roboto_Condensed-Medium.ttf")
        font_id = QFontDatabase.addApplicationFont(font_path)
        font_families = QFontDatabase.applicationFontFamilies(font_id)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 524)
        MainWindow.setMinimumSize(QtCore.QSize(347, 524))
        MainWindow.setMaximumSize(QtCore.QSize(347, 524))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-40, 0, 451, 71))
        self.frame.setStyleSheet("background-color: rgb(79, 79, 79);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pageTitle = QtWidgets.QLabel(self.frame)
        self.pageTitle.setGeometry(QtCore.QRect(50, 12, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(22)
        self.pageTitle.setFont(font)
        self.pageTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.pageTitle.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.pageTitle.setObjectName("pageTitle")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(8, 470, 333, 41))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 80, 331, 381))
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        for file in os.listdir("C:/Glassy"):
            if re.match(r"xe\d+", file):
                self.listWidget.addItem(f"Google XE {file.replace("xe", "")}")
            elif "aosp5" in file:
                self.listWidget.addItem("AOSP 5.1.1")

        self.pushButton.clicked.connect(self.DeleteFirmware)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def DeleteFirmware(self):
        try:
            if "AOSP" in self.listWidget.currentItem().text():
                shutil.rmtree("C:/Glassy/aosp5/")
                msg = QMessageBox()

                msg.setWIndowTitle("AOSP 5.1.1")
                msg.setText("AOSP 5.1.1 firmware has been successfully removed")


                msg.exec_()

                self.listWidget.takeItem(self.listWidget.currentRow())
            else:
                firmware_name = self.listWidget.currentItem().text()
                file_name = "xe" + self.listWidget.currentItem().text().replace("Google XE ", "")
                shutil.rmtree(f"C:/Glassy/{file_name}")
                msg = QMessageBox()

                msg.setWindowTitle(firmware_name)
                msg.setText(f"{firmware_name} has been successfully removed")

                msg.exec_()

                self.listWidget.takeItem(self.listWidget.currentRow())
        except Exception as e:

            print(e)

            msg = QMessageBox()

            msg.setWindowTitle("Error")
            msg.setText(f"Check console for details")

            msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Glassy"))
        self.pageTitle.setText(_translate("MainWindow", "Downloaded firmwares"))
        self.pushButton.setText(_translate("MainWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Firmwares()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
