# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\screens\device_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from PyQt5.QtGui import QFontDatabase
from change_time import ChangeTime
from programs import Programs
from delete import Remove
import subprocess
import requests
import json
import os
import shutil
import time
import threading
from art import text2art
import ctypes

ctypes.windll.shcore.SetProcessDpiAwareness(0)

base_dir = os.path.dirname(__file__)

print(text2art("GLASSY"))
print("Version: 1.0 PRE-RELEASE 1")
print("Developed by zeroxdev")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        font_path = os.path.join(base_dir, "./fonts/Roboto_Condensed-Medium.ttf")
        font_id = QFontDatabase.addApplicationFont(font_path)
        font_families = QFontDatabase.applicationFontFamilies(font_id)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 557)
        MainWindow.setMinimumSize(QtCore.QSize(1065, 557))
        MainWindow.setMaximumSize(QtCore.QSize(2121212, 557))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -10, 1091, 91))
        self.frame.setStyleSheet("background-color: rgb(79, 79, 79);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pageTitle = QtWidgets.QLabel(self.frame)
        self.pageTitle.setGeometry(QtCore.QRect(780, 30, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(22)
        self.pageTitle.setFont(font)
        self.pageTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.pageTitle.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.pageTitle.setObjectName("pageTitle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -3, 231, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/logo.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.deviceFrame = QtWidgets.QFrame(self.centralwidget)
        self.deviceFrame.setGeometry(QtCore.QRect(0, 80, 1071, 521))
        self.deviceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.deviceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.deviceFrame.setObjectName("deviceFrame")
        self.frame_2 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_2.setGeometry(QtCore.QRect(20, 50, 201, 171))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 201, 141))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/glass.png")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.deviceFrame)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.rebootButton = QtWidgets.QPushButton(self.deviceFrame)
        self.rebootButton.setGeometry(QtCore.QRect(17, 228, 101, 31))
        self.rebootButton.setObjectName("rebootButton")
        self.fastbootButton = QtWidgets.QPushButton(self.deviceFrame)
        self.fastbootButton.setGeometry(QtCore.QRect(120, 228, 101, 31))
        self.fastbootButton.setObjectName("fastbootButton")
        self.batteryText = QtWidgets.QLabel(self.deviceFrame)
        self.batteryText.setGeometry(QtCore.QRect(20, 270, 181, 21))
        self.batteryText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.batteryText.setObjectName("batteryText")
        self.line = QtWidgets.QFrame(self.deviceFrame)
        self.line.setGeometry(QtCore.QRect(20, 260, 201, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.batteryText_2 = QtWidgets.QLabel(self.deviceFrame)
        self.batteryText_2.setGeometry(QtCore.QRect(20, 290, 181, 21))
        self.batteryText_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.batteryText_2.setObjectName("batteryText_2")
        self.applicationsText = QtWidgets.QLabel(self.deviceFrame)
        self.applicationsText.setGeometry(QtCore.QRect(20, 310, 181, 21))
        self.applicationsText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.applicationsText.setObjectName("applicationsText")
        self.line_2 = QtWidgets.QFrame(self.deviceFrame)
        self.line_2.setGeometry(QtCore.QRect(20, 330, 201, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.apkInstallButton = QtWidgets.QPushButton(self.deviceFrame)
        self.apkInstallButton.setGeometry(QtCore.QRect(10, 350, 121, 23))
        self.apkInstallButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apkInstallButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.apkInstallButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/install.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.apkInstallButton.setIcon(icon)
        self.apkInstallButton.setIconSize(QtCore.QSize(25, 25))
        self.apkInstallButton.setObjectName("apkInstallButton")
        self.progressBar = QtWidgets.QProgressBar(self.deviceFrame)
        self.progressBar.setGeometry(QtCore.QRect(-10, 460, 1101, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label_5 = QtWidgets.QLabel(self.deviceFrame)
        self.label_5.setGeometry(QtCore.QRect(250, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.uninstallButton = QtWidgets.QPushButton(self.deviceFrame)
        self.uninstallButton.setGeometry(QtCore.QRect(4, 380, 121, 23))
        self.uninstallButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uninstallButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uninstallButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/uninstall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uninstallButton.setIcon(icon1)
        self.uninstallButton.setIconSize(QtCore.QSize(25, 25))
        self.uninstallButton.setObjectName("uninstallButton")
        self.updatesButton = QtWidgets.QPushButton(self.deviceFrame)
        self.updatesButton.setGeometry(QtCore.QRect(0, 410, 121, 31))
        self.updatesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updatesButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.updatesButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/updates.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updatesButton.setIcon(icon2)
        self.updatesButton.setIconSize(QtCore.QSize(35, 35))
        self.updatesButton.setObjectName("updatesButton")
        self.frame_4 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_4.setGeometry(QtCore.QRect(250, 50, 781, 91))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(10, -2, 91, 101))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/launchy.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(110, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(110, 40, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_8.setObjectName("label_8")
        self.installLaunchy = QtWidgets.QPushButton(self.deviceFrame)
        self.installLaunchy.setGeometry(QtCore.QRect(910, 80, 101, 41))
        self.installLaunchy.setObjectName("installLaunchy")
        self.frame_5 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_5.setGeometry(QtCore.QRect(250, 160, 781, 91))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(10, -2, 91, 91))
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/clock.png")))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(110, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(110, 40, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_11.setObjectName("label_11")
        self.changeTimeButton = QtWidgets.QPushButton(self.deviceFrame)
        self.changeTimeButton.setGeometry(QtCore.QRect(910, 190, 101, 41))
        self.changeTimeButton.setObjectName("changeTimeButton")
        self.frame_6 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_6.setGeometry(QtCore.QRect(250, 270, 471, 91))
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setGeometry(QtCore.QRect(20, 15, 61, 61))
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/cmd.png")))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(110, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        self.label_14.setGeometry(QtCore.QRect(110, 40, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_14.setObjectName("label_14")
        self.commandsExecuteButton = QtWidgets.QPushButton(self.deviceFrame)
        self.commandsExecuteButton.setGeometry(QtCore.QRect(600, 297, 101, 41))
        self.commandsExecuteButton.setObjectName("commandsExecuteButton")
        self.frame_7 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_7.setGeometry(QtCore.QRect(730, 270, 301, 91))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setGeometry(QtCore.QRect(20, 15, 61, 61))
        self.label_15.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/programs.png")))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setGeometry(QtCore.QRect(110, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setGeometry(QtCore.QRect(110, 40, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_17.setObjectName("label_17")
        self.showButton = QtWidgets.QPushButton(self.deviceFrame)
        self.showButton.setGeometry(QtCore.QRect(950, 296, 71, 41))
        self.showButton.setObjectName("showButton")
        self.frame_8 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_8.setGeometry(QtCore.QRect(250, 380, 781, 61))
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_33 = QtWidgets.QLabel(self.frame_8)
        self.label_33.setGeometry(QtCore.QRect(20, 5, 51, 51))
        self.label_33.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/android.png")))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_8)
        self.label_34.setGeometry(QtCore.QRect(110, 17, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_34.setObjectName("label_34")
        self.installFastbootdriversButton = QtWidgets.QPushButton(self.deviceFrame)
        self.installFastbootdriversButton.setGeometry(QtCore.QRect(850, 390, 161, 41))
        self.installFastbootdriversButton.setObjectName("installFastbootdriversButton")
        self.searchingFrame = QtWidgets.QFrame(self.centralwidget)
        self.searchingFrame.setGeometry(QtCore.QRect(0, 80, 1071, 521))
        self.searchingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchingFrame.setObjectName("searchingFrame")
        self.label_35 = QtWidgets.QLabel(self.searchingFrame)
        self.label_35.setGeometry(QtCore.QRect(0, 200, 1071, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.searchingFrame)
        self.label_36.setGeometry(QtCore.QRect(520, 150, 41, 41))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/loading.png")))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.doesntDetectButton = QtWidgets.QPushButton(self.searchingFrame)
        self.doesntDetectButton.setGeometry(QtCore.QRect(370, 250, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doesntDetectButton.setFont(font)
        self.doesntDetectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doesntDetectButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 174, 255);")
        self.doesntDetectButton.setObjectName("doesntDetectButton")
        self.updatingPage = QtWidgets.QFrame(self.centralwidget)
        self.updatingPage.setGeometry(QtCore.QRect(0, 80, 1071, 521))
        self.updatingPage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.updatingPage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.updatingPage.setObjectName("updatingPage")
        self.frame_3 = QtWidgets.QFrame(self.updatingPage)
        self.frame_3.setGeometry(QtCore.QRect(20, 50, 201, 341))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_37 = QtWidgets.QLabel(self.frame_3)
        self.label_37.setGeometry(QtCore.QRect(0, 100, 201, 141))
        self.label_37.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/glass.png")))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.updatingPage)
        self.label_38.setGeometry(QtCore.QRect(20, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.rebootIntoSystemButton = QtWidgets.QPushButton(self.updatingPage)
        self.rebootIntoSystemButton.setGeometry(QtCore.QRect(20, 396, 201, 31))
        self.rebootIntoSystemButton.setObjectName("rebootIntoSystemButton")
        self.label_39 = QtWidgets.QLabel(self.updatingPage)
        self.label_39.setGeometry(QtCore.QRect(240, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.installXE24Button = QtWidgets.QPushButton(self.updatingPage)
        self.installXE24Button.setGeometry(QtCore.QRect(20, 430, 201, 31))
        self.installXE24Button.setObjectName("installXE24Button")
        self.statusText = QtWidgets.QLabel(self.updatingPage)
        self.statusText.setGeometry(QtCore.QRect(240, 390, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusText.setFont(font)
        self.statusText.setObjectName("statusText")
        self.progressBar_3 = QtWidgets.QProgressBar(self.updatingPage)
        self.progressBar_3.setGeometry(QtCore.QRect(240, 440, 801, 21))
        self.progressBar_3.setMaximum(0)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setObjectName("progressBar_3")
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.updatingPage.hide()
        self.deviceFrame.hide()

        searchThread = threading.Thread(target=self.DeviceSearching)
        searchThread.start()

        self.rebootButton.clicked.connect(self.reboot_device_button)
        self.rebootIntoSystemButton.clicked.connect(self.exit_fastboot)
        self.fastbootButton.clicked.connect(self.reboot_fastboot_button)
        self.apkInstallButton.clicked.connect(self.install_apk_init)
        self.installLaunchy.clicked.connect(self.install_launchy_init)
        self.commandsExecuteButton.clicked.connect(lambda: self.run_command_as_admin("C:/Glassy/platform_tools/adb.exe shell"))
        self.installFastbootdriversButton.clicked.connect(self.install_fastboot_driver_init)
        self.changeTimeButton.clicked.connect(self.OpenChangeDateTime)
        self.showButton.clicked.connect(self.OpenPrograms)
        self.doesntDetectButton.clicked.connect(self.InstallADBDrivers)
        self.updatesButton.clicked.connect(self.InstallXE24_Init)
        self.installXE24Button.clicked.connect(self.InstallXE24ButtonClick)
        self.uninstallButton.clicked.connect(self.OpenDeleteMenu)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def InstallXE24_Init(self):
        os.system("C:/Glassy/platform_tools/adb.exe reboot-bootloader")
        self.deviceFrame.hide()
        self.updatingPage.hide()
        self.searchingFrame.show()

        self.label_35.setText("Waiting for device in FastBoot...")

        searchThread = threading.Thread(target=self.FindDeviceAndErase)
        searchThread.start()


    def InstallXE24ButtonClick(self):
        self.installXE24Button.setText("Installing ...")
        eraseThread = threading.Thread(target=self.FindDeviceAndErase)
        eraseThread.start()

    def FindDeviceAndErase(self):
        while True:
                command = subprocess.run(
                        ["C:/Glassy/platform_tools/fastboot.exe", "devices"],
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        text=True
                )

                if "fastboot" in command.stdout.strip():
                        self.label_35.setText("Connecting to device...")
                        time.sleep(1)
                        self.searchingFrame.hide()
                        self.updatingPage.show()
                        break
        
        time.sleep(1)

        self.statusText.setText("Device detected!")
        time.sleep(1)
        self.statusText.setText("Unlocking bootloader ...")
        os.system("C:/Glassy/platform_tools/fastboot.exe oem unlock")
        os.system("C:/Glassy/platform_tools/fastboot.exe oem unlock")
        self.statusText.setText("Flashing BOOT.IMG (5496 KB) ...")
        os.system("C:/Glassy/platform_tools/fastboot.exe flash boot C:/Glassy/firmware/boot.img")
        self.statusText.setText("Flashing SYSTEM.IMG (627202 KB) ...")
        os.system("C:/Glassy/platform_tools/fastboot.exe flash system C:/Glassy/firmware/system.img")
        self.statusText.setText("Flashing RECOVERY.IMG (6196 KB) ...")
        os.system("C:/Glassy/platform_tools/fastboot.exe flash recovery C:/Glassy/firmware/recovery.img")
        self.statusText.setText("Erasing cache and userdata ...")
        os.system("C:/Glassy/platform_tools/fastboot.exe erase cache")
        os.system("C:/Glassy/platform_tools/fastboot.exe erase userdata")

        self.statusText.setText("Rebooting ...")
        time.sleep(1)
        os.system("C:/Glassy/platform_tools/fastboot.exe reboot")

        self.statusText.setText("Done.")
        self.progressBar_3.setValue(100)


        


    def InstallADBDrivers(self):
        msg = QMessageBox()

        msg.setWindowTitle("Driver")
        msg.setText("Which driver do you want to install?")

        adb_btn = msg.addButton("ADB", QMessageBox.YesRole)
        fastboot_btn = msg.addButton("FastBoot", QMessageBox.YesRole)
        msg.exec_()

        if msg.clickedButton() == adb_btn:
            self.run_command_as_admin(command='start C:/Glassy/drivers/adb/Latest-ADB-Installer.bat')
        else:
                msg2 = QMessageBox()

                msg2.setWindowTitle("TestSigning")
                msg2.setText("Do you have TestSigning enabled?")

                yes_btn = msg2.addButton("Yes", QMessageBox.YesRole)
                no_btn = msg2.addButton("No", QMessageBox.YesRole)
                idk_btn = msg2.addButton("I dont know", QMessageBox.YesRole)

                msg2.exec_()

                if msg2.clickedButton() == yes_btn:
                        installThread = threading.Thread(target=self.install_fastboot_driver)
                        installThread.start()
                else:
                        msg3 = QMessageBox()

                        msg3.setWindowTitle("TestSigning")
                        msg3.setText("Okay, now we will enable TestSigning to install the driver and restart your computer. After enabling it, open the program, click 'Install fastboot driver' again and select Yes.")

                        msg3.exec_()

                        self.run_command_as_admin(command="start C:/Glassy/drivers/fastboot/testsigning.bat")

    def OpenDeleteMenu(self):
        self.delete_window = QtWidgets.QMainWindow()
        self.delete_ui = Remove()
        self.delete_ui.setupUi(self.delete_window)

        self.delete_window.show()

    def OpenPrograms(self):
        self.showButton.setText("Loading...")
        self.programs_window = QtWidgets.QMainWindow()
        self.programs_ui = Programs()
        self.programs_ui.setupUi(self.programs_window)

        self.programs_window.show()

        self.showButton.setText("Show")

    def OpenChangeDateTime(self):
        self.change_time_window = QtWidgets.QMainWindow()
        self.change_time_ui = ChangeTime()
        self.change_time_ui.setupUi(self.change_time_window)

        self.change_time_window.show()

    def install_fastboot_driver_init(self):
        msg = QMessageBox()

        msg.setWindowTitle("TestSigning")
        msg.setText("Do you have TestSigning enabled?")

        yes_btn = msg.addButton("Yes", QMessageBox.YesRole)
        no_btn = msg.addButton("No", QMessageBox.YesRole)
        idk_btn = msg.addButton("I dont know", QMessageBox.YesRole)

        msg.exec_()

        if msg.clickedButton() == yes_btn:
                installThread = threading.Thread(target=self.install_fastboot_driver)
                installThread.start()
        else:
                msg2 = QMessageBox()

                msg2.setWindowTitle("TestSigning")
                msg2.setText("Okay, now we will enable TestSigning to install the driver and restart your computer. After enabling it, open the program, click 'Install fastboot driver' again and select Yes.")

                msg2.exec_()

                self.run_command_as_admin(command="start C:/Glassy/drivers/fastboot/testsigning.bat")

    

    def install_fastboot_driver(self):
        self.progressBar.setValue(100)
        self.run_command_as_admin(command="start C:/Glassy/drivers/fastboot/install.bat")

    def reboot_device_button(self):
        self.rebootButton.setText("Rebooting ...")
        os.system("C:/Glassy/platform_tools/adb.exe reboot")
        self.rebootButton.setText("Reboot")
        
        self.deviceFrame.hide()
        self.updatingPage.hide()
        self.searchingFrame.show()

        self.label_35.setText("Connect your glasses to continue")

        searchThread = threading.Thread(target=self.DeviceSearching)
        searchThread.start()

    def exit_fastboot(self):
        self.rebootIntoSystemButton.setText("Rebooting ...")
        os.system("C:/Glassy/platform_tools/fastboot.exe reboot")
        self.rebootIntoSystemButton.setText("Reboot")
        
        self.deviceFrame.hide()
        self.updatingPage.hide()
        self.searchingFrame.show()

        self.label_35.setText("Connect your glasses to continue")

        searchThread = threading.Thread(target=self.DeviceSearching)
        searchThread.start()



    def run_command_as_admin(self, command: str):
        ps_command = f'Start-Process cmd -Verb RunAs -ArgumentList "/c {command}"'
        
        result = subprocess.run(
                ['powershell', '-Command', ps_command],
                capture_output=True,
                text=True
        )

    def reboot_fastboot_button(self):
        self.fastbootButton.setText("Rebooting ...")
        os.system("C:/Glassy/platform_tools/adb.exe reboot-bootloader")
        self.fastbootButton.setText("Enter fastboot")
        
        self.deviceFrame.hide()
        self.searchingFrame.show()

        self.label_35.setText("Waiting for device in FastBoot...")

        searchThread = threading.Thread(target=self.DeviceSearching)
        searchThread.start()

    def install_apk_init(self):
        file_path, _ = QFileDialog.getOpenFileName(
            self.apkInstallButton,
            "Choose APK file",
            "",
            "Все файлы (*.*)"
        )
        if file_path:
            installThread = threading.Thread(target=lambda: self.install_apk(file=file_path))
            installThread.start()

    def install_apk(self, file):
        
        self.progressBar.setValue(0)

        self.apkInstallButton.setText("      Installing...")

        os.system(f'C:/Glassy/platform_tools/adb.exe install "{file}"')

        self.apkInstallButton.setText(" Install .APK file")

        self.progressBar.setValue(100)

    def install_launchy_init(self):
        installThread = threading.Thread(target=self.install_launchy)
        installThread.start()

    def install_launchy(self):
        self.progressBar.setValue(0)
        self.installLaunchy.setText("Installing...")
        os.system(f'C:/Glassy/platform_tools/adb.exe install "C:/Glassy/android_apps/launchy.apk"')
        self.progressBar.setValue(100)
        self.installLaunchy.setText("Installed")

    def update_device_info(self):
        battery = 0
        firmware = ""
        applications = 0

        command = subprocess.run(
                ["C:/Glassy/platform_tools/adb.exe", "shell", "dumpsys", "battery"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
        )

        for line in command.stdout.splitlines():
            if "level" in line:
                battery = int(line.replace("level: ", ""))
        
        command = subprocess.run(
                ["C:/Glassy/platform_tools/adb.exe", "shell", "getprop", "ro.build.version.glass"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
        )

        firmware = command.stdout.strip()

        command = subprocess.run(
                ["C:/Glassy/platform_tools/adb.exe", "shell", "pm", "list", "packages"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
        )


        for line in command.stdout.splitlines():
            applications += 1

        self.batteryText.setText(f"Battery: {battery}%")
        self.applicationsText.setText(f"Applications: {str(applications / 2).replace(".0", "")}")
        self.batteryText_2.setText(f"Firmware: {firmware}")


    def DeviceSearching(self):
        while True:
            command = subprocess.run(
                ["C:/Glassy/platform_tools/adb.exe", "devices"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )

            linecount = 0

            for line in command.stdout.splitlines():
                linecount += 1

            if linecount == 3:
                self.label_35.setText("Connecting to device...")
                self.batteryText.setText("Battery: Loading...")
                self.applicationsText.setText("Applications: Loading...")
                self.batteryText_2.setText("Firmware: Loading...")
                time.sleep(1)
                self.searchingFrame.hide()
                self.deviceFrame.show()
                self.update_device_info()
                sys.exit()
            else:
                command = subprocess.run(
                        ["C:/Glassy/platform_tools/fastboot.exe", "devices"],
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        text=True
                )

                if "fastboot" in command.stdout.strip():
                    self.label_35.setText("Connecting to device...")
                    time.sleep(1)
                    self.searchingFrame.hide()
                    self.updatingPage.show()
                    sys.exit()

                

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Glassy"))
        self.pageTitle.setText(_translate("MainWindow", "My Device"))
        self.label_3.setText(_translate("MainWindow", "Device Info"))
        self.rebootButton.setText(_translate("MainWindow", "Reboot"))
        self.fastbootButton.setText(_translate("MainWindow", "Enter fastboot"))
        self.batteryText.setText(_translate("MainWindow", "Battery: 100%"))
        self.batteryText_2.setText(_translate("MainWindow", "Firmware: XE24"))
        self.applicationsText.setText(_translate("MainWindow", "Applications: 57"))
        self.apkInstallButton.setText(_translate("MainWindow", " Install .APK file"))
        self.label_5.setText(_translate("MainWindow", "Useful features"))
        self.uninstallButton.setText(_translate("MainWindow", " Uninstall app"))
        self.updatesButton.setText(_translate("MainWindow", "Install XE24"))
        self.label_7.setText(_translate("MainWindow", "Install Launchy?"))
        self.label_8.setText(_translate("MainWindow", "Launch apps installed via ADB directly from the glasses without connecting to a computer."))
        self.installLaunchy.setText(_translate("MainWindow", "Install"))
        self.label_10.setText(_translate("MainWindow", "Change time "))
        self.label_11.setText(_translate("MainWindow", "Change the time on your Google Glass"))
        self.changeTimeButton.setText(_translate("MainWindow", "Change"))
        self.label_13.setText(_translate("MainWindow", "Command Line"))
        self.label_14.setText(_translate("MainWindow", "Execute commands on your Glass"))
        self.commandsExecuteButton.setText(_translate("MainWindow", "Start"))
        self.label_16.setText(_translate("MainWindow", "Programs"))
        self.label_17.setText(_translate("MainWindow", "List of programs"))
        self.showButton.setText(_translate("MainWindow", "Show"))
        self.label_34.setText(_translate("MainWindow", "Install Fastboot Drivers"))
        self.installFastbootdriversButton.setText(_translate("MainWindow", "Install"))
        self.label_35.setText(_translate("MainWindow", "Connect your glasses to continue"))
        self.doesntDetectButton.setText(_translate("MainWindow", "The program doesn\'t detect the device?"))
        self.label_38.setText(_translate("MainWindow", "Device Info"))
        self.rebootIntoSystemButton.setText(_translate("MainWindow", "Exit fastboot"))
        self.label_39.setText(_translate("MainWindow", "Status"))
        self.installXE24Button.setText(_translate("MainWindow", "Install XE24"))
        self.statusText.setText(_translate("MainWindow", "Waiting ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
