# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\screens\device_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from PyQt5.QtGui import QFontDatabase
from change_time import ChangeTime
from programs import Programs
from delete import Remove
from art import text2art
from zipfile import ZipFile

import subprocess
import requests
import json
import os
import shutil
import time
import threading
import ctypes

ctypes.windll.shcore.SetProcessDpiAwareness(0)

base_dir = os.path.dirname(__file__)

print(text2art("Glassy"))
print("Version: 1.0")
print("Developed by zeroxdev")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        font_path = os.path.join(base_dir, "./fonts/Roboto_Condensed-Medium.ttf")
        font_id = QFontDatabase.addApplicationFont(font_path)
        font_families = QFontDatabase.applicationFontFamilies(font_id)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1068, 557)
        MainWindow.setMinimumSize(QtCore.QSize(1068, 557))
        MainWindow.setMaximumSize(QtCore.QSize(1068, 557))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -10, 1091, 91))
        self.frame.setStyleSheet("background-color: rgb(79, 79, 79);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pageTitle = QtWidgets.QLabel(self.frame)
        self.pageTitle.setGeometry(QtCore.QRect(780, 30, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(22)
        self.pageTitle.setFont(font)
        self.pageTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.pageTitle.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.pageTitle.setObjectName("pageTitle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -3, 231, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/logo.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.deviceFrame = QtWidgets.QFrame(self.centralwidget)
        self.deviceFrame.setGeometry(QtCore.QRect(0, 80, 1071, 521))
        self.deviceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.deviceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.deviceFrame.setObjectName("deviceFrame")
        self.frame_2 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_2.setGeometry(QtCore.QRect(20, 50, 201, 171))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 201, 141))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/glass.png")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.deviceFrame)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.rebootButton = QtWidgets.QPushButton(self.deviceFrame)
        self.rebootButton.setGeometry(QtCore.QRect(17, 228, 101, 31))
        self.rebootButton.setObjectName("rebootButton")
        self.fastbootButton = QtWidgets.QPushButton(self.deviceFrame)
        self.fastbootButton.setGeometry(QtCore.QRect(120, 228, 101, 31))
        self.fastbootButton.setObjectName("fastbootButton")
        self.batteryText = QtWidgets.QLabel(self.deviceFrame)
        self.batteryText.setGeometry(QtCore.QRect(20, 270, 181, 21))
        self.batteryText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.batteryText.setObjectName("batteryText")
        self.line = QtWidgets.QFrame(self.deviceFrame)
        self.line.setGeometry(QtCore.QRect(20, 260, 201, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.batteryText_2 = QtWidgets.QLabel(self.deviceFrame)
        self.batteryText_2.setGeometry(QtCore.QRect(20, 290, 181, 21))
        self.batteryText_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.batteryText_2.setObjectName("batteryText_2")
        self.applicationsText = QtWidgets.QLabel(self.deviceFrame)
        self.applicationsText.setGeometry(QtCore.QRect(20, 310, 181, 21))
        self.applicationsText.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.applicationsText.setObjectName("applicationsText")
        self.line_2 = QtWidgets.QFrame(self.deviceFrame)
        self.line_2.setGeometry(QtCore.QRect(20, 330, 201, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.apkInstallButton = QtWidgets.QPushButton(self.deviceFrame)
        self.apkInstallButton.setGeometry(QtCore.QRect(40, 350, 81, 23))
        self.apkInstallButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apkInstallButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.apkInstallButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.apkInstallButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.apkInstallButton.setIconSize(QtCore.QSize(25, 25))
        self.apkInstallButton.setAutoDefault(False)
        self.apkInstallButton.setDefault(False)
        self.apkInstallButton.setFlat(False)
        self.apkInstallButton.setObjectName("apkInstallButton")
        self.progressBar = QtWidgets.QProgressBar(self.deviceFrame)
        self.progressBar.setGeometry(QtCore.QRect(-10, 460, 1101, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label_5 = QtWidgets.QLabel(self.deviceFrame)
        self.label_5.setGeometry(QtCore.QRect(250, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.uninstallButton = QtWidgets.QPushButton(self.deviceFrame)
        self.uninstallButton.setGeometry(QtCore.QRect(41, 380, 71, 23))
        self.uninstallButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uninstallButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uninstallButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.uninstallButton.setIconSize(QtCore.QSize(25, 25))
        self.uninstallButton.setFlat(False)
        self.uninstallButton.setObjectName("uninstallButton")
        self.updatesButton = QtWidgets.QPushButton(self.deviceFrame)
        self.updatesButton.setGeometry(QtCore.QRect(15, 410, 91, 31))
        self.updatesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updatesButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.updatesButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.updatesButton.setIconSize(QtCore.QSize(35, 35))
        self.updatesButton.setObjectName("updatesButton")
        self.frame_4 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_4.setGeometry(QtCore.QRect(250, 50, 781, 91))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(10, -2, 91, 101))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/launchy.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(110, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(110, 40, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_8.setObjectName("label_8")
        self.installLaunchy = QtWidgets.QPushButton(self.deviceFrame)
        self.installLaunchy.setGeometry(QtCore.QRect(910, 80, 101, 41))
        self.installLaunchy.setObjectName("installLaunchy")
        self.frame_5 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_5.setGeometry(QtCore.QRect(250, 160, 781, 91))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(10, -2, 91, 91))
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/clock.png")))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(110, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(110, 40, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_11.setObjectName("label_11")
        self.changeTimeButton = QtWidgets.QPushButton(self.deviceFrame)
        self.changeTimeButton.setGeometry(QtCore.QRect(910, 190, 101, 41))
        self.changeTimeButton.setObjectName("changeTimeButton")
        self.frame_6 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_6.setGeometry(QtCore.QRect(250, 270, 471, 91))
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setGeometry(QtCore.QRect(20, 15, 61, 61))
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/cmd.png")))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(110, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        self.label_14.setGeometry(QtCore.QRect(110, 40, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_14.setObjectName("label_14")
        self.commandsExecuteButton = QtWidgets.QPushButton(self.deviceFrame)
        self.commandsExecuteButton.setGeometry(QtCore.QRect(600, 297, 101, 41))
        self.commandsExecuteButton.setObjectName("commandsExecuteButton")
        self.frame_7 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_7.setGeometry(QtCore.QRect(730, 270, 301, 91))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setGeometry(QtCore.QRect(20, 15, 61, 61))
        self.label_15.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/programs.png")))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setGeometry(QtCore.QRect(110, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setGeometry(QtCore.QRect(110, 40, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_17.setObjectName("label_17")
        self.showButton = QtWidgets.QPushButton(self.deviceFrame)
        self.showButton.setGeometry(QtCore.QRect(950, 296, 71, 41))
        self.showButton.setObjectName("showButton")
        self.frame_8 = QtWidgets.QFrame(self.deviceFrame)
        self.frame_8.setGeometry(QtCore.QRect(250, 380, 781, 61))
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_33 = QtWidgets.QLabel(self.frame_8)
        self.label_33.setGeometry(QtCore.QRect(30, 5, 51, 51))
        self.label_33.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/android.png")))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_8)
        self.label_34.setGeometry(QtCore.QRect(110, 15, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_34.setObjectName("label_34")
        self.installFastbootdriversButton = QtWidgets.QPushButton(self.deviceFrame)
        self.installFastbootdriversButton.setGeometry(QtCore.QRect(850, 390, 161, 41))
        self.installFastbootdriversButton.setObjectName("installFastbootdriversButton")
        self.label_2 = QtWidgets.QLabel(self.deviceFrame)
        self.label_2.setGeometry(QtCore.QRect(20, 350, 21, 21))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/install.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_18 = QtWidgets.QLabel(self.deviceFrame)
        self.label_18.setGeometry(QtCore.QRect(20, 380, 21, 21))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/uninstall.png")))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.deviceFrame)
        self.label_19.setGeometry(QtCore.QRect(20, 414, 21, 27))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/updates.png")))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.searchingFrame = QtWidgets.QFrame(self.centralwidget)
        self.searchingFrame.setGeometry(QtCore.QRect(0, 80, 1071, 521))
        self.searchingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchingFrame.setObjectName("searchingFrame")
        self.label_20 = QtWidgets.QLabel(self.searchingFrame)
        self.label_20.setGeometry(QtCore.QRect(0, 200, 1071, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.searchingFrame)
        self.label_21.setGeometry(QtCore.QRect(520, 150, 41, 41))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/loading.png")))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.doesntDetectButton = QtWidgets.QPushButton(self.searchingFrame)
        self.doesntDetectButton.setGeometry(QtCore.QRect(370, 250, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doesntDetectButton.setFont(font)
        self.doesntDetectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doesntDetectButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 174, 255);")
        self.doesntDetectButton.setObjectName("doesntDetectButton")
        self.updatingPage = QtWidgets.QFrame(self.centralwidget)
        self.updatingPage.setGeometry(QtCore.QRect(0, 80, 1071, 521))
        self.updatingPage.setMaximumSize(QtCore.QSize(2112121, 2121212))
        self.updatingPage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.updatingPage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.updatingPage.setObjectName("updatingPage")
        self.frame_3 = QtWidgets.QFrame(self.updatingPage)
        self.frame_3.setGeometry(QtCore.QRect(20, 50, 201, 341))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setGeometry(QtCore.QRect(0, 100, 201, 141))
        self.label_22.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px solid white;")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/glass.png")))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.updatingPage)
        self.label_23.setGeometry(QtCore.QRect(20, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.rebootIntoSystemButton = QtWidgets.QPushButton(self.updatingPage)
        self.rebootIntoSystemButton.setGeometry(QtCore.QRect(20, 396, 201, 31))
        self.rebootIntoSystemButton.setObjectName("rebootIntoSystemButton")
        self.label_24 = QtWidgets.QLabel(self.updatingPage)
        self.label_24.setGeometry(QtCore.QRect(240, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.installXE24Button = QtWidgets.QPushButton(self.updatingPage)
        self.installXE24Button.setGeometry(QtCore.QRect(20, 430, 201, 31))
        self.installXE24Button.setObjectName("installXE24Button")
        self.statusText = QtWidgets.QLabel(self.updatingPage)
        self.statusText.setGeometry(QtCore.QRect(240, 390, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusText.setFont(font)
        self.statusText.setObjectName("statusText")
        self.progressBar_2 = QtWidgets.QProgressBar(self.updatingPage)
        self.progressBar_2.setGeometry(QtCore.QRect(240, 440, 801, 21))
        self.progressBar_2.setMaximum(0)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.radioButton = QtWidgets.QRadioButton(self.updatingPage)
        self.radioButton.setGeometry(QtCore.QRect(250, 90, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.updatingPage)
        self.radioButton_2.setGeometry(QtCore.QRect(250, 140, 191, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_25 = QtWidgets.QLabel(self.updatingPage)
        self.label_25.setGeometry(QtCore.QRect(240, 50, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.customRomFrame = QtWidgets.QFrame(self.updatingPage)
        self.customRomFrame.setGeometry(QtCore.QRect(260, 160, 421, 131))
        self.customRomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.customRomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.customRomFrame.setObjectName("customRomFrame")
        self.bootInput = QtWidgets.QLineEdit(self.customRomFrame)
        self.bootInput.setGeometry(QtCore.QRect(10, 10, 291, 21))
        self.bootInput.setObjectName("bootInput")
        self.systemInput = QtWidgets.QLineEdit(self.customRomFrame)
        self.systemInput.setGeometry(QtCore.QRect(10, 40, 291, 21))
        self.systemInput.setObjectName("systemInput")
        self.recoveryInput = QtWidgets.QLineEdit(self.customRomFrame)
        self.recoveryInput.setGeometry(QtCore.QRect(10, 70, 291, 21))
        self.recoveryInput.setObjectName("recoveryInput")
        self.selectBootFile = QtWidgets.QPushButton(self.customRomFrame)
        self.selectBootFile.setGeometry(QtCore.QRect(310, 10, 91, 23))
        self.selectBootFile.setObjectName("selectBootFile")
        self.selectSystemFile = QtWidgets.QPushButton(self.customRomFrame)
        self.selectSystemFile.setGeometry(QtCore.QRect(310, 40, 91, 23))
        self.selectSystemFile.setObjectName("selectSystemFile")
        self.selectRecoveryFile = QtWidgets.QPushButton(self.customRomFrame)
        self.selectRecoveryFile.setGeometry(QtCore.QRect(310, 70, 91, 23))
        self.selectRecoveryFile.setObjectName("selectRecoveryFile")
        self.radioButton_3 = QtWidgets.QRadioButton(self.updatingPage)
        self.radioButton_3.setGeometry(QtCore.QRect(250, 116, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.updatingPage.hide()
        self.deviceFrame.hide()
        self.customRomFrame.hide()

        searchThread = threading.Thread(target=self.DeviceSearching)
        searchThread.start()

        self.rebootButton.clicked.connect(self.reboot_device_button)
        self.rebootIntoSystemButton.clicked.connect(self.exit_fastboot)
        self.fastbootButton.clicked.connect(self.reboot_fastboot_button)
        self.apkInstallButton.clicked.connect(self.install_apk_init)
        self.installLaunchy.clicked.connect(self.install_launchy_init)
        self.commandsExecuteButton.clicked.connect(lambda: self.run_command_as_admin("C:/Glassy/platform_tools/adb.exe shell"))
        self.installFastbootdriversButton.clicked.connect(self.install_fastboot_driver_init)
        self.changeTimeButton.clicked.connect(self.OpenChangeDateTime)
        self.showButton.clicked.connect(self.OpenPrograms)
        self.doesntDetectButton.clicked.connect(self.InstallADBDrivers)
        self.updatesButton.clicked.connect(self.InstallXE24_Init)
        self.installXE24Button.clicked.connect(self.InstallXE24ButtonClick)
        self.uninstallButton.clicked.connect(self.OpenDeleteMenu)

        self.radioButton.clicked.connect(self.CheckRadioButtons)
        self.radioButton_2.clicked.connect(self.CheckRadioButtons)
        self.radioButton_3.clicked.connect(self.CheckRadioButtons)

        self.selectBootFile.clicked.connect(self.SelectBootFile)
        self.selectRecoveryFile.clicked.connect(self.SelectRecoveryFile)
        self.selectSystemFile.clicked.connect(self.SelectSystemFile)

        self.progressBar_2.setMaximum(100)
        self.statusText.setText("")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def SelectBootFile(self):
        file_path, _ = QFileDialog.getOpenFileName(
            self.apkInstallButton,
            "Choose boot.img file",
            "",
            "Все файлы (*.*)"
        )

        if file_path:
             self.bootInput.setText(file_path)

    def SelectRecoveryFile(self):
        file_path, _ = QFileDialog.getOpenFileName(
            self.apkInstallButton,
            "Choose recovery.img file",
            "",
            "Все файлы (*.*)"
        )

        if file_path:
             self.recoveryInput.setText(file_path)

    def SelectSystemFile(self):
        file_path, _ = QFileDialog.getOpenFileName(
            self.apkInstallButton,
            "Choose system.img file",
            "",
            "Все файлы (*.*)"
        )

        if file_path:
             self.systemInput.setText(file_path)

    def CheckRadioButtons(self):
         if self.radioButton_2.isChecked() != True:
              self.customRomFrame.hide()
         else:
              self.customRomFrame.show()

    def InstallXE24_Init(self):
        self.radioButton.setChecked(True)
        self.radioButton_2.setChecked(False)
        os.system("C:/Glassy/platform_tools/adb.exe reboot-bootloader")
        self.deviceFrame.hide()
        self.updatingPage.hide()
        self.searchingFrame.show()

        self.label_20.setText("Waiting for device in FastBoot...")

        searchThread = threading.Thread(target=self.DeviceSearching)
        searchThread.start()


    def InstallXE24ButtonClick(self):
        self.installXE24Button.setEnabled(False)
        self.installXE24Button.setText("Installing ...")
        self.progressBar_2.setMaximum(0)
        self.statusText.setText("Waiting for device ...")
        eraseThread = threading.Thread(target=self.FindDeviceAndErase)
        eraseThread.start()

    def FindDeviceAndErase(self):
        while True:
                command = subprocess.run(
                        ["C:/Glassy/platform_tools/fastboot.exe", "devices"],
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        text=True
                )

                if "fastboot" in command.stdout.strip():
                        self.label_20.setText("Connecting to device...")
                        time.sleep(1)
                        self.searchingFrame.hide()
                        self.updatingPage.show()
                        break
        
        time.sleep(1)

        self.statusText.setText("Device detected!")
        time.sleep(1)
        self.statusText.setText("Unlocking bootloader ...")
        os.system("C:/Glassy/platform_tools/fastboot.exe oem unlock")
        os.system("C:/Glassy/platform_tools/fastboot.exe oem unlock")
        if self.radioButton.isChecked() == True:
                self.statusText.setText("Flashing boot.img (5496 KB) ...")
                os.system("C:/Glassy/platform_tools/fastboot.exe flash boot C:/Glassy/firmware/boot.img")
                self.statusText.setText("Flashing system.img (627202 KB) ...")
                os.system("C:/Glassy/platform_tools/fastboot.exe flash system C:/Glassy/firmware/system.img")
                self.statusText.setText("Flashing recovery.img (6196 KB) ...")
                os.system("C:/Glassy/platform_tools/fastboot.exe flash recovery C:/Glassy/firmware/recovery.img")
                self.statusText.setText("Erasing cache and userdata ...")
                os.system("C:/Glassy/platform_tools/fastboot.exe erase cache")
                os.system("C:/Glassy/platform_tools/fastboot.exe erase userdata")
        elif self.radioButton_2.isChecked() == True:
             if self.systemInput.text() != "" and self.bootInput.text() != "":
                self.statusText.setText("Flashing system.img ...")
                os.system(f'C:/Glassy/platform_tools/fastboot.exe flash system "{self.systemInput.text()}"')
                self.statusText.setText("Flashing boot.img ...")
                os.system(f'C:/Glassy/platform_tools/fastboot.exe flash boot "{self.bootInput.text()}"')
                if self.recoveryInput.text() != "":
                     self.statusText.setText("Flashing recovery.img ...")
                     os.system(f'C:/Glassy/platform_tools/fastboot.exe flash recovery "{self.recoveryInput.text()}"')
                self.statusText.setText("Erasing cache and userdata ...")
                os.system("C:/Glassy/platform_tools/fastboot.exe erase cache")
                os.system("C:/Glassy/platform_tools/fastboot.exe erase userdata")
        elif self.radioButton_3.isChecked() == True:
             if os.path.exists("C:/Glassy/aosp5/system.img") and os.path.exists("C:/Glassy/aosp5/boot.img"):
                  self.statusText.setText("Flashing system.img ...")
                  os.system("C:/Glassy/platform_tools/fastboot.exe flash system C:/Glassy/aosp5/system.img")
                  self.statusText.setText("Flashing boot.img ...")
                  os.system("C:/Glassy/platform_tools/fastboot.exe flash boot C:/Glassy/aosp5/boot.img")
                  self.statusText.setText("Erasing cache and userdata ...")
                  os.system("C:/Glassy/platform_tools/fastboot.exe erase cache")
                  os.system("C:/Glassy/platform_tools/fastboot.exe erase userdata")
             else:
                  if os.path.exists("C:/Glassy/aosp5/"):
                       shutil.rmtree("C:/Glassy/aosp5")
                  self.statusText.setText("Requesting download link...")
                  os.chdir("C:/Glassy/")
                  os.mkdir("aosp5")
                  os.chdir("aosp5")
                  response = requests.get(url="https://glassy-f1645-default-rtdb.firebaseio.com/link.json")
                  urlToDownload = f"https://drop.xtrafrancyz.net/selif/{response.json()}"
                  self.statusText.setText("Downloading AOSP 5.1.1 ...")
                  r = requests.get(url=urlToDownload)
                  with open("aosp5.zip", "wb") as file:
                       file.write(r.content)

                  self.statusText.setText("Unpacking ...")
                  aospZip = ZipFile(file="aosp5.zip")
                  aospZip.extractall()
                  aospZip.close()
                  os.remove("aosp5.zip")
                  self.statusText.setText("Flashing system.img ...")
                  os.system("C:/Glassy/platform_tools/fastboot.exe flash system C:/Glassy/aosp5/system.img")
                  self.statusText.setText("Flashing boot.img ...")
                  os.system("C:/Glassy/platform_tools/fastboot.exe flash boot C:/Glassy/aosp5/boot.img")
                  self.statusText.setText("Erasing cache and userdata ...")
                  os.system("C:/Glassy/platform_tools/fastboot.exe erase cache")
                  os.system("C:/Glassy/platform_tools/fastboot.exe erase userdata")

        self.statusText.setText("Rebooting ...")
        time.sleep(1)
        os.system("C:/Glassy/platform_tools/fastboot.exe reboot")

        self.statusText.setText("")

        self.installXE24Button.setEnabled(True)
        self.installXE24Button.setText("Install")
        self.progressBar_2.setMaximum(100)

        self.updatingPage.hide()
        self.deviceFrame.hide()
        self.searchingFrame.show()

        searchThread = threading.Thread(target=self.DeviceSearching)
        searchThread.start()

        self.label_20.setText("Connect your glasses to continue")

        sys.exit()
        


        


    def InstallADBDrivers(self):
        msg = QMessageBox()

        msg.setWindowTitle("Driver")
        msg.setText("Which driver do you want to install?")

        adb_btn = msg.addButton("ADB", QMessageBox.YesRole)
        fastboot_btn = msg.addButton("FastBoot", QMessageBox.YesRole)
        msg.exec_()

        if msg.clickedButton() == adb_btn:
            self.run_command_as_admin(command='start C:/Glassy/drivers/adb/Latest-ADB-Installer.bat')
        else:
                msg2 = QMessageBox()

                msg2.setWindowTitle("TestSigning")
                msg2.setText("Do you have TestSigning enabled?")

                yes_btn = msg2.addButton("Yes", QMessageBox.YesRole)
                no_btn = msg2.addButton("No", QMessageBox.YesRole)
                idk_btn = msg2.addButton("I dont know", QMessageBox.YesRole)

                msg2.exec_()

                if msg2.clickedButton() == yes_btn:
                        installThread = threading.Thread(target=self.install_fastboot_driver)
                        installThread.start()
                else:
                        msg3 = QMessageBox()

                        msg3.setWindowTitle("TestSigning")
                        msg3.setText("Okay, now we will enable TestSigning to install the driver and restart your computer. After enabling it, open the program, click 'Install fastboot driver' again and select Yes.")

                        msg3.exec_()

                        self.run_command_as_admin(command="start C:/Glassy/drivers/fastboot/testsigning.bat")

    def OpenDeleteMenu(self):
        self.delete_window = QtWidgets.QMainWindow()
        self.delete_ui = Remove()
        self.delete_ui.setupUi(self.delete_window)

        self.delete_window.show()

    def OpenPrograms(self):
        self.showButton.setText("Loading...")
        self.programs_window = QtWidgets.QMainWindow()
        self.programs_ui = Programs()
        self.programs_ui.setupUi(self.programs_window)

        self.programs_window.show()

        self.showButton.setText("Show")

    def OpenChangeDateTime(self):
        self.change_time_window = QtWidgets.QMainWindow()
        self.change_time_ui = ChangeTime()
        self.change_time_ui.setupUi(self.change_time_window)

        self.change_time_window.show()

    def install_fastboot_driver_init(self):
        msg = QMessageBox()

        msg.setWindowTitle("TestSigning")
        msg.setText("Do you have TestSigning enabled?")

        yes_btn = msg.addButton("Yes", QMessageBox.YesRole)
        no_btn = msg.addButton("No", QMessageBox.YesRole)
        idk_btn = msg.addButton("I dont know", QMessageBox.YesRole)

        msg.exec_()

        if msg.clickedButton() == yes_btn:
                installThread = threading.Thread(target=self.install_fastboot_driver)
                installThread.start()
        else:
                msg2 = QMessageBox()

                msg2.setWindowTitle("TestSigning")
                msg2.setText("Okay, now we will enable TestSigning to install the driver and restart your computer. After enabling it, open the program, click 'Install fastboot driver' again and select Yes.")

                msg2.exec_()

                self.run_command_as_admin(command="start C:/Glassy/drivers/fastboot/testsigning.bat")

    

    def install_fastboot_driver(self):
        self.progressBar.setValue(100)
        self.run_command_as_admin(command="start C:/Glassy/drivers/fastboot/install.bat")

    def reboot_device_button(self):
        self.rebootButton.setText("Rebooting ...")
        os.system("C:/Glassy/platform_tools/adb.exe reboot")
        self.rebootButton.setText("Reboot")
        
        self.deviceFrame.hide()
        self.updatingPage.hide()
        self.searchingFrame.show()

        self.label_20.setText("Connect your glasses to continue")

        searchThread = threading.Thread(target=self.DeviceSearching)
        searchThread.start()

    def exit_fastboot(self):
        self.rebootIntoSystemButton.setText("Rebooting ...")
        os.system("C:/Glassy/platform_tools/fastboot.exe reboot")
        self.rebootIntoSystemButton.setText("Reboot")
        
        self.deviceFrame.hide()
        self.updatingPage.hide()
        self.searchingFrame.show()

        self.label_20.setText("Connect your glasses to continue")

        searchThread = threading.Thread(target=self.DeviceSearching)
        searchThread.start()



    def run_command_as_admin(self, command: str):
        ps_command = f'Start-Process cmd -Verb RunAs -ArgumentList "/c {command}"'
        
        result = subprocess.run(
                ['powershell', '-Command', ps_command],
                capture_output=True,
                text=True
        )

    def reboot_fastboot_button(self):
        self.fastbootButton.setText("Rebooting ...")
        os.system("C:/Glassy/platform_tools/adb.exe reboot-bootloader")
        self.fastbootButton.setText("Enter fastboot")
        
        self.deviceFrame.hide()
        self.searchingFrame.show()

        self.label_20.setText("Waiting for device in FastBoot...")

        searchThread = threading.Thread(target=self.DeviceSearching)
        searchThread.start()

    def install_apk_init(self):
        file_path, _ = QFileDialog.getOpenFileName(
            self.apkInstallButton,
            "Choose APK file",
            "",
            "Все файлы (*.*)"
        )
        if file_path:
            installThread = threading.Thread(target=lambda: self.install_apk(file=file_path))
            installThread.start()

    def install_apk(self, file):
        
        self.progressBar.setValue(0)

        self.apkInstallButton.setText("Installing...")

        self.progressBar.setMaximum(0)

        os.system(f'C:/Glassy/platform_tools/adb.exe install "{file}"')

        self.apkInstallButton.setText(" Install .APK file")

        self.progressBar.setMaximum(100)

    def install_launchy_init(self):
        installThread = threading.Thread(target=self.install_launchy)
        installThread.start()

    def install_launchy(self):
        self.progressBar.setMaximum(0)
        self.installLaunchy.setText("Installing...")
        os.system(f'C:/Glassy/platform_tools/adb.exe install "C:/Glassy/android_apps/launchy.apk"')
        self.progressBar.setMaximum(100)
        self.installLaunchy.setText("Installed")

    def update_device_info(self):
        battery = 0
        firmware = ""
        applications = 0

        command = subprocess.run(
                ["C:/Glassy/platform_tools/adb.exe", "shell", "dumpsys", "battery"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
        )

        for line in command.stdout.splitlines():
            if "level" in line:
                battery = int(line.replace("level: ", ""))
        
        command = subprocess.run(
                ["C:/Glassy/platform_tools/adb.exe", "shell", "getprop", "ro.build.version.glass"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
        )

        firmware = command.stdout.strip()

        command = subprocess.run(
                ["C:/Glassy/platform_tools/adb.exe", "shell", "pm", "list", "packages"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
        )


        for line in command.stdout.splitlines():
            applications += 1

        self.batteryText.setText(f"Battery: {battery}%")
        self.applicationsText.setText(f"Applications: {str(applications / 2).replace(".0", "")}")
        self.batteryText_2.setText(f"Firmware: {firmware}")


    def DeviceSearching(self):
        while True:
            command = subprocess.run(
                ["C:/Glassy/platform_tools/adb.exe", "devices"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )

            linecount = 0

            for line in command.stdout.splitlines():
                linecount += 1

            if linecount == 3:
                self.label_20.setText("Connecting to device...")
                self.batteryText.setText("Battery: Loading...")
                self.applicationsText.setText("Applications: Loading...")
                self.batteryText_2.setText("Firmware: Loading...")
                time.sleep(1)
                self.searchingFrame.hide()
                self.deviceFrame.show()
                self.update_device_info()
                sys.exit()
            else:
                command = subprocess.run(
                        ["C:/Glassy/platform_tools/fastboot.exe", "devices"],
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        text=True
                )

                if "fastboot" in command.stdout.strip():
                    self.label_20.setText("Connecting to device...")
                    time.sleep(1)
                    self.searchingFrame.hide()
                    self.updatingPage.show()
                    sys.exit()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Glassy"))
        self.pageTitle.setText(_translate("MainWindow", "My Device"))
        self.label_3.setText(_translate("MainWindow", "Device Info"))
        self.rebootButton.setText(_translate("MainWindow", "Reboot"))
        self.fastbootButton.setText(_translate("MainWindow", "Enter fastboot"))
        self.batteryText.setText(_translate("MainWindow", "Battery: 100%"))
        self.batteryText_2.setText(_translate("MainWindow", "Firmware: XE24"))
        self.applicationsText.setText(_translate("MainWindow", "Applications: 57"))
        self.apkInstallButton.setText(_translate("MainWindow", " Install .APK file"))
        self.label_5.setText(_translate("MainWindow", "Useful features"))
        self.uninstallButton.setText(_translate("MainWindow", " Uninstall app"))
        self.updatesButton.setText(_translate("MainWindow", "Erase"))
        self.label_7.setText(_translate("MainWindow", "Install Launchy?"))
        self.label_8.setText(_translate("MainWindow", "Launch apps installed via ADB directly from the glasses without connecting to a computer."))
        self.installLaunchy.setText(_translate("MainWindow", "Install"))
        self.label_10.setText(_translate("MainWindow", "Change time "))
        self.label_11.setText(_translate("MainWindow", "Change the time on your Google Glass"))
        self.changeTimeButton.setText(_translate("MainWindow", "Change"))
        self.label_13.setText(_translate("MainWindow", "Command Line"))
        self.label_14.setText(_translate("MainWindow", "Execute commands on your Glass"))
        self.commandsExecuteButton.setText(_translate("MainWindow", "Start"))
        self.label_16.setText(_translate("MainWindow", "Programs"))
        self.label_17.setText(_translate("MainWindow", "List of programs"))
        self.showButton.setText(_translate("MainWindow", "Show"))
        self.label_34.setText(_translate("MainWindow", "Install Fastboot Drivers"))
        self.installFastbootdriversButton.setText(_translate("MainWindow", "Install"))
        self.label_20.setText(_translate("MainWindow", "Connect your glasses to continue"))
        self.doesntDetectButton.setText(_translate("MainWindow", "The program doesn\'t detect the device?"))
        self.label_23.setText(_translate("MainWindow", "Device Info"))
        self.rebootIntoSystemButton.setText(_translate("MainWindow", "Exit fastboot"))
        self.label_24.setText(_translate("MainWindow", "Installation"))
        self.installXE24Button.setText(_translate("MainWindow", "Install"))
        self.statusText.setText(_translate("MainWindow", "Waiting ..."))
        self.radioButton.setText(_translate("MainWindow", "Install XE24"))
        self.radioButton_2.setText(_translate("MainWindow", "Custom"))
        self.label_25.setText(_translate("MainWindow", "What firmware do you want to install?"))
        self.bootInput.setPlaceholderText(_translate("MainWindow", "Select boot.img file ..."))
        self.systemInput.setPlaceholderText(_translate("MainWindow", "Select system.img file ..."))
        self.recoveryInput.setPlaceholderText(_translate("MainWindow", "Select recovery.img file (optional) ..."))
        self.selectBootFile.setText(_translate("MainWindow", "Select"))
        self.selectSystemFile.setText(_translate("MainWindow", "Select"))
        self.selectRecoveryFile.setText(_translate("MainWindow", "Select"))
        self.radioButton_3.setText(_translate("MainWindow", "Install AOSP 5.1.1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
